Addition of  multiplication instructions to Risc-V PMP case study
katamaran-project/katamaran pull request #43
Opened 2023-11-09 10:48 UTC by fvogels

Added support for `MUL`/`MULH`/`MULHU`/`MULHSU` to the Risc-V PMP case study.
Everything builds fine after having made the changes.

2023-11-09 14:42 UTC, capt-hb requested changes
See discussion on Slack.

2023-11-13 14:37 UTC, fvogels commented
I've updated `fun_execute_RTYPE` so that the code looks more like the original Sail implementation. There is some duplication though, I would like to move the code into a separate function that deals with all 4 multiplication instructions (with parameters `high`, `signed1` and `signed2` parameters like in the Sail implementation) but I'm running into some trouble with the context.

Could you let me know if this new implementation is what you had in mind?

2023-11-13 14:42 UTC, capt-hb commented
This is already closer to what I expected, but you should indeed define a separate function with the parameters you mention (as in the Sail spec). The `MUL` instructions are not part of the `RTYPE` execution clause.

Could you implement the change you mention (`execute_MUL`)? If you run into issues then we should have a look at what is going wrong.

2023-11-13 15:01 UTC, fvogels commented
If you're in the office we can look at it.

2023-11-13 16:07 UTC, fvogels commented
I've added a `execute_MUL` function, but still need to find a way to call it from within `fun_execute_RTYPE`.
I can't call it directly as it's not really a function, but my intention is to be investigating `call`.
That'll have to be for tomorrow though.

2023-11-14 06:33 UTC, capt-hb commented
This is looking good, there's still one remaining issue though. You are still modifying the `execute_RTYPE` function, that should not be the case.
In Sail the `execute` function is a scattered definition. We keep those scattered parts as individual functions (e.g., `execute_RTYPE`, `execute_MUL`, ...), but we need to tie them back to the "top-level" `execute` function. This function is defined here: [fun_execute](https://github.com/katamaran-project/katamaran/blob/b7d951c28fc8a0ef6297b91b3531df98b7ee52f0/case_study/RiscvPmp/Machine.v#L1006).
To add your "scattered clause" (`execute_MUL`), you will need to have a look at how for example `RTYPE` here works. Essentially, the parameters passed to your `execute_MUL` function come from the `decode` function, [postulated here](https://github.com/katamaran-project/katamaran/blob/b7d951c28fc8a0ef6297b91b3531df98b7ee52f0/case_study/RiscvPmp/Machine.v#L129). This decoder will produce something of the form [MUL](https://github.com/riscv/sail-riscv/blob/69af65cf41220a12dd4a62308c7dff537157f757/model/riscv_insts_mext.sail#L76) (which you need to add in `Base.v`) and contains all the parameters that will get passed to your `execute_MUL`.

2023-11-14 11:55 UTC, skeuchel approved these changes
LGTM

2023-11-14 11:55 UTC, skeuchel commented on case_study/RiscvPmp/Machine.v
> +                     then exp_unop (@uop.signed _ xlen) rs1_val
Did you have to explicitly pass the bitvector length here? Would've thought it can figure that one out.

2023-11-14 12:21 UTC, fvogels commented on case_study/RiscvPmp/Machine.v
> +                     then exp_unop (@uop.signed _ xlen) rs1_val
The explicit length is indeed no longer necessary. I'll remove it.

2023-11-15 06:53 UTC, capt-hb approved these changes

2023-11-20 14:46 UTC, merged